#!/usr/bin/env python3
"""
kf-compile.py — KnowledgeForge compiler.

Reads canonical module specs from knowledgeforge-core/modules/, applies
platform bindings, and writes compiled output to a target variant repo.

Usage:
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo
    python3 compiler/kf-compile.py --target claude-projects --output /path/to/cp-repo
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo --dry-run
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo --diff

Exit codes:
    0 — success
    1 — binding/module errors
    2 — output write errors
"""

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("[kf-compile] PyYAML required: pip install pyyaml\n")
    sys.exit(1)

# Resolve paths relative to this script (works regardless of cwd)
CORE_ROOT = Path(__file__).parent.parent
MODULES_DIR = CORE_ROOT / "modules"
BINDINGS_DIR = CORE_ROOT / "platform-bindings"
HOOKS_DIR = CORE_ROOT / "hooks"


# ---------------------------------------------------------------------------
# Section extraction
# ---------------------------------------------------------------------------


# Section names that delimit compilation blocks. The extractor only stops
# when it hits another CC marker — internal ## headings in embedded content
# are passed through unchanged.
CC_SECTION_MARKERS = frozenset({"CC Skill", "CC Doc", "CC Agent", "CC Rules"})

# Sections to STRIP from -CP output. Superset of CC_SECTION_MARKERS plus
# "Section-Load Map" — the latter only ever appears as a compile-side back-
# reference inside a CC body, but the strip filter names it explicitly as a
# safety net against future canonical drift (if it ever moves outside a CC
# block, it must still be stripped from -CP).
CP_STRIP_MARKERS = CC_SECTION_MARKERS | frozenset({"Section-Load Map"})


def extract_section(content: str, section_name: str) -> str | None:
    """
    Extract everything between '## {section_name}' and the next CC section marker.

    Stops only on '## CC Skill', '## CC Doc', '## CC Agent', '## CC Rules' —
    NOT on arbitrary ## headings inside the embedded content.

    Returns None if the section is not found.
    Strips leading/trailing whitespace from the extracted block.
    """
    lines = content.split("\n")
    in_section = False
    result = []

    for line in lines:
        stripped = line.strip()
        if stripped == f"## {section_name}":
            in_section = True
            continue
        if in_section:
            # Stop only at another CC section marker, not regular headings.
            # Also stops on titled variants (e.g., "## CC Skill — KF Fit Check")
            # by checking whether the suffix starts with a known marker followed
            # by a space (handles " — " and similar separators).
            if line.startswith("## "):
                section_id = line[3:].strip()
                if section_id in CC_SECTION_MARKERS or any(
                    section_id.startswith(m + " ") for m in CC_SECTION_MARKERS
                ):
                    break
            result.append(line)

    if not in_section:
        return None

    return "\n".join(result).strip()


def add_compile_header(content: str, source_module: str, output_type: str,
                        version: str) -> str:
    """Prepend a small compilation metadata comment to generated files.

    Deterministic: no timestamp. Per-run timestamp lives in
    .kf-compile-manifest.json which is the authoritative compile log.
    Embedding a timestamp here caused timestamp-only diffs to fire the
    cc/cp workflow change-detection and open noop PRs (bead `rxc`).
    """
    header = (
        f"<!-- Generated by kf-compile | source: {source_module} "
        f"| type: {output_type} | version: {version} -->\n"
    )
    return header + content


def heading_to_anchor(text: str) -> str:
    """Convert a markdown heading to a GitHub-compatible anchor.

    GitHub's algorithm: lowercase, strip all non-alphanumeric/space/hyphen chars,
    replace spaces with hyphens, collapse runs of hyphens.

    '## Full PDIA Method'  → '#full-pdia-method'
    '## Bias Detection'    → '#bias-detection'
    '## When to Calibrate' → '#when-to-calibrate'
    """
    anchor = text.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)   # strip punctuation except hyphens
    anchor = re.sub(r"\s+", "-", anchor)        # spaces → hyphens
    anchor = re.sub(r"-{2,}", "-", anchor)      # collapse multiple hyphens
    return "#" + anchor.strip("-")


def generate_section_toc(content: str, min_headings: int = 2) -> str | None:
    """Generate a compact inline TOC from ## headings in extracted content.

    Returns a markdown line like:
        **Sections:** [When to Calibrate](#when-to-calibrate) · [Multi-Run Protocol](#multi-run-protocol)

    Returns None when fewer than min_headings ## headings are found (no point
    generating a TOC for a single-section file).

    Only indexes ## level — # (title) and ### (sub-items) are excluded.

    Headings containing '→' (navigation hints, file path references) have the
    path part stripped for display: 'Section-Load Map → ~/.claude/...' becomes
    'Section-Load Map' in the TOC link, anchored to the cleaned text.
    """
    headings = []
    for line in content.split("\n"):
        if line.startswith("## "):
            text = line[3:].strip()
            if not text:
                continue
            # Strip ' → path' suffixes — use only the label before the arrow
            display = text.split("→")[0].strip() if "→" in text else text
            headings.append((display, heading_to_anchor(display)))

    if len(headings) < min_headings:
        return None

    links = " · ".join(f"[{display}]({anchor})" for display, anchor in headings)
    return f"**Sections:** {links}"


def inject_toc(compiled_content: str, raw_content: str, out_type: str) -> str:
    """Inject a section TOC into compiled content after the compile header.

    Only fires for doc/skill/agent types with 2+ ## headings.
    Rules and verbatim copies are left unchanged.

    Placement:
    - Doc/Skill: TOC immediately after the compile header comment.
    - Agent: TOC after the YAML frontmatter block (--- ... ---) so the
      frontmatter stays machine-parseable at file top.
    """
    if out_type not in ("doc", "skill", "agent"):
        return compiled_content

    toc = generate_section_toc(raw_content)
    if toc is None:
        return compiled_content

    # compiled_content = "<!-- header -->\n{body}"
    header_line, body = compiled_content.split("\n", 1)

    if out_type == "agent":
        # Agent files have YAML frontmatter: ---\n...\n---\n
        # Inject TOC after the closing --- so frontmatter stays intact.
        body_stripped = body.lstrip("\n")
        if body_stripped.startswith("---\n"):
            closing = body_stripped.find("\n---\n", 4)
            if closing != -1:
                frontmatter = body_stripped[: closing + 5]   # up to and including ---\n
                rest = body_stripped[closing + 5 :]
                return f"{header_line}\n{frontmatter}\n{toc}\n\n---\n{rest}"
        # No frontmatter found — fall through to default placement

    return f"{header_line}\n\n{toc}\n\n---\n{body}"


def linkify_claude_paths(content: str, out_path: Path, output_root: Path) -> str:
    """Convert `~/.claude/path.md` references in Section-Load Maps to relative links.

    Maps `~/.claude/` → `{output_root}/.claude/` then computes a relative path
    from out_path's parent directory to the referenced file.

    Pattern forms handled:
      `~/.claude/X.md`              → [X.md](relative/X.md)
      `~/.claude/X.md` → Section   → [X.md#section-anchor](relative/X.md#section-anchor)

    The regex only matches backtick-delimited `~/.claude/` paths so false
    positives outside Section-Load Map blocks are negligible.
    """
    claude_root = output_root / ".claude"
    out_dir = out_path.parent

    def replace_path(match: re.Match) -> str:
        path_part = match.group(1)      # e.g., "skills/kf/builder.md"
        section_hint = match.group(2)   # e.g., "Builder accretion section" or None

        # Map ~/.claude/X → absolute target in variant repo
        abs_target = claude_root / path_part

        # Relative path from output file's directory to the target
        try:
            rel = Path(os.path.relpath(abs_target, out_dir)).as_posix()
        except ValueError:
            # Different drive on Windows — return original unchanged
            return match.group(0)

        display = Path(path_part).name

        anchor = ""
        if section_hint:
            anchor = heading_to_anchor(section_hint.strip())

        return f"[{display}]({rel}{anchor})"

    # Match: `~/.claude/{path.md}` optionally followed by ` → {section text}`
    # group 1: path after ~/.claude/
    # group 2: optional section name after →  (to end of line, non-greedy)
    pattern = r'`~/\.claude/([^`]+\.md)`(?:\s*→\s*([^\n`]+?))?(?=\s*\n|\s*$)'

    return re.sub(pattern, replace_path, content, flags=re.MULTILINE)


# ---------------------------------------------------------------------------
# Module loader
# ---------------------------------------------------------------------------

def load_module(module_num: str) -> tuple[str, str] | tuple[None, None]:
    """
    Load a module file by two-digit prefix number.

    Returns (filename, content) or (None, None) if not found.
    """
    pattern = f"{module_num}_*.md"
    matches = list(MODULES_DIR.glob(pattern))
    if not matches:
        return None, None
    return matches[0].name, matches[0].read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Platform binding loader
# ---------------------------------------------------------------------------

def load_binding(target: str) -> dict:
    binding_path = BINDINGS_DIR / f"{target}.yaml"
    if not binding_path.exists():
        sys.stderr.write(f"[kf-compile] Binding not found: {binding_path}\n")
        sys.exit(1)
    with open(binding_path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Divergence detection
# ---------------------------------------------------------------------------

_COMPILE_HEADER_RE = re.compile(
    r"^<!-- Generated by kf-compile [^>]*-->\n", re.MULTILINE
)


def strip_compile_header(content: str) -> str:
    """Strip the kf-compile sentinel header so timestamp drift doesn't false-flag.

    Only removes the first match at the start of the file. Files without the
    header (e.g., claude-projects full-file output) pass through unchanged.
    """
    return _COMPILE_HEADER_RE.sub("", content, count=1)


def detect_divergence(out_path: Path, new_content: str) -> str | None:
    """Return a one-line reason if writing new_content would clobber hand edits.

    Compares body-of-existing to body-of-new (compile header stripped on both
    sides). If they differ in any non-header byte, the existing file has been
    edited outside the compile pipeline and overwriting would lose work.

    Returns None when overwrite is safe (file missing, or differs only by
    compile-header timestamp).
    """
    if not out_path.exists():
        return None
    try:
        existing = out_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return f"unreadable target ({e.__class__.__name__})"
    if strip_compile_header(existing) == strip_compile_header(new_content):
        return None
    old_lines = len(existing.splitlines())
    new_lines = len(new_content.splitlines())
    return f"hand-edited (target {old_lines} lines vs source {new_lines} lines)"


# ---------------------------------------------------------------------------
# Module-level frontmatter parser (cc_rules / cc_hooks — added 7.5.0)
# ---------------------------------------------------------------------------

_MODULE_METADATA_HEADING_RE = re.compile(r"^## Module Metadata\s*$", re.MULTILINE)
_YAML_FENCE_OPEN_RE = re.compile(r"^```yaml\s*$", re.MULTILINE)
_YAML_FENCE_CLOSE_RE = re.compile(r"^```\s*$", re.MULTILINE)


def parse_module_metadata(module_content: str) -> dict:
    """Extract and parse the YAML block right after '## Module Metadata'.

    Returns a dict like {"module": {...}, "cc_rules": [...], "cc_hooks": [...]}.
    Empty dict if no metadata block is found or YAML parse fails.
    """
    heading = _MODULE_METADATA_HEADING_RE.search(module_content)
    if not heading:
        return {}
    fence_open = _YAML_FENCE_OPEN_RE.search(module_content, heading.end())
    if not fence_open:
        return {}
    fence_close = _YAML_FENCE_CLOSE_RE.search(module_content, fence_open.end())
    if not fence_close:
        return {}
    yaml_text = module_content[fence_open.end():fence_close.start()]
    try:
        parsed = yaml.safe_load(yaml_text) or {}
        if not isinstance(parsed, dict):
            return {}
        return parsed
    except yaml.YAMLError as e:
        sys.stderr.write(f"[kf-compile] parse_module_metadata: YAML error — {e}\n")
        return {}


def emit_cc_rules_for_module(filename: str, module_content: str, metadata: dict,
                              output_root: Path, emit_fn,
                              version: str) -> list[Path]:
    """Compile cc_rules entries from a module's metadata into .claude/rules/kf/*.md.

    Each cc_rules entry produces one path-gated rule file with `paths:` frontmatter.
    body_section names the markdown section (e.g., "CC Rules — TypeScript imports")
    whose body is the rule content. Section heading convention uses `CC Rules — X`
    (plural) to match the existing CC_SECTION_MARKERS startswith logic.

    Returns the list of paths written (for orphan cleanup).
    """
    cc_rules = metadata.get("cc_rules") or []
    written = []
    for rule_entry in cc_rules:
        try:
            rule_filename = rule_entry["filename"]
            paths_globs = rule_entry["paths"]
            body_section = rule_entry["body_section"]
        except KeyError as e:
            sys.stderr.write(
                f"[kf-compile] cc_rules entry in {filename} missing required key {e}; "
                f"skipping entry\n"
            )
            continue

        out_path = output_root / ".claude/rules/kf" / rule_filename
        body = extract_section(module_content, body_section)
        if body is None:
            sys.stderr.write(
                f"[kf-compile] cc_rules: section '## {body_section}' not found in "
                f"{filename} — skipping {rule_filename}\n"
            )
            continue

        paths_yaml = yaml.safe_dump({"paths": paths_globs},
                                    default_flow_style=False,
                                    sort_keys=False).rstrip()
        header = (
            f"<!-- Generated by kf-compile from {filename} cc_rules: "
            f"{rule_filename} | version {version} -->\n"
        )
        content = f"{header}---\n{paths_yaml}\n---\n\n{body}"
        emit_fn(filename, out_path, content, f"cc_rules:{rule_filename}")
        written.append(out_path)
    return written


def cleanup_orphan_rules(written_paths: set[Path], rules_dir: Path,
                          output_root: Path, dry_run: bool, diff_mode: bool,
                          manifest: list[dict]) -> None:
    """Delete any pre-existing .md file in .claude/rules/kf/ not in written_paths.

    Compile is idempotent on this dir: removing a cc_rules entry from a module
    deletes the file on next compile. Subdirs are NOT recursed — kf-runtime/
    is a separate partition owned by the M21 accretion loop.
    """
    if not rules_dir.exists():
        return
    for existing in rules_dir.iterdir():
        if not existing.is_file() or existing.suffix != ".md":
            continue
        if existing in written_paths:
            continue
        rel = str(existing.relative_to(output_root))
        if dry_run or diff_mode:
            manifest.append({
                "source": "cc_rules:orphan_cleanup",
                "output": rel,
                "section": "orphan",
                "status": "would_delete",
            })
        else:
            existing.unlink()
            manifest.append({
                "source": "cc_rules:orphan_cleanup",
                "output": rel,
                "section": "orphan",
                "status": "deleted",
            })


def collect_cc_hooks_entry(filename: str, hook_entry: dict) -> tuple[str, dict] | None:
    """Validate a single cc_hooks entry and return (event, hook_dict).

    Returns None on malformed entry (logged to stderr).
    """
    try:
        event = hook_entry["hook_event"]
        command = hook_entry["command"]
    except KeyError as e:
        sys.stderr.write(
            f"[kf-compile] cc_hooks entry in {filename} missing required key {e}; "
            f"skipping entry\n"
        )
        return None

    built = {
        "type": hook_entry.get("type", "command"),
        "command": command,
        "matcher": hook_entry.get("matcher", {}),
    }
    source_rule = hook_entry.get("source_rule")
    if source_rule:
        built["_kf_source_rule"] = source_rule
    return event, built


def emit_settings_fragment(hooks_aggregate: dict, output_root: Path,
                            dry_run: bool, diff_mode: bool, manifest: list[dict],
                            version: str) -> None:
    """Write .claude/settings.kf.json if hooks_aggregate is non-empty; skip otherwise.

    Per Phase 2 spec Section 5: at v1 no module ships cc_hooks entries, so the
    aggregate is empty and we OMIT the file entirely (don't emit `{}`).
    """
    if not hooks_aggregate:
        return

    fragment = {
        "kf_hooks": hooks_aggregate,
        "_kf_compiled_at": datetime.now(timezone.utc).isoformat(),
        "_kf_version": version,
    }
    out_path = output_root / ".claude/settings.kf.json"
    content = json.dumps(fragment, indent=2) + "\n"
    rel = str(out_path.relative_to(output_root))
    entry = {
        "source": "cc_settings_fragment",
        "output": rel,
        "section": "compiled",
    }
    if dry_run:
        entry["status"] = "would_write"
    elif diff_mode:
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        entry["status"] = "unchanged" if content == existing else "changed"
    else:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        entry["status"] = "written"
    entry["bytes"] = len(content.encode())
    manifest.append(entry)


# ---------------------------------------------------------------------------
# Compilers per platform
# ---------------------------------------------------------------------------

def compile_claude_code(binding: dict, output_root: Path, dry_run: bool,
                         diff_mode: bool, version: str,
                         check_divergence: bool = False) -> list[dict]:
    """
    Compile for the claude-code platform.

    Returns a manifest list: [{source, output, section, status, bytes}]
    """
    manifest = []

    def emit(source: str, out_path: Path, content: str, section: str):
        entry = {"source": source, "output": str(out_path.relative_to(output_root)),
                 "section": section}
        if diff_mode:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if content == existing:
                entry["status"] = "unchanged"
            else:
                entry["status"] = "changed"
                # Show a small diff summary
                old_lines = len(existing.splitlines())
                new_lines = len(content.splitlines())
                entry["diff_summary"] = f"{old_lines} → {new_lines} lines"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            if check_divergence:
                reason = detect_divergence(out_path, content)
                if reason:
                    entry["status"] = "diverged"
                    entry["diverged_reason"] = reason
                    entry["bytes"] = len(content.encode())
                    manifest.append(entry)
                    return
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            entry["status"] = "written"
        entry["bytes"] = len(content.encode())
        manifest.append(entry)

    module_outputs = binding.get("module_outputs", {})

    # Phase 2 (7.5.0) — per-module cc_rules accumulator + cross-module cc_hooks aggregator
    all_written_rules: set[Path] = set()
    cc_hooks_aggregate: dict[str, list[dict]] = {}

    for module_num, module_spec in module_outputs.items():
        filename, module_content = load_module(module_num)
        if module_content is None:
            sys.stderr.write(f"[kf-compile] Module {module_num} not found — skipping\n")
            continue

        for output_def in module_spec.get("outputs", []):
            out_type = output_def["type"]
            out_path = output_root / output_def["path"]
            section = output_def.get("section")

            if section:
                extracted = extract_section(module_content, section)
                if extracted is None:
                    sys.stderr.write(
                        f"[kf-compile] WARNING: section '## {section}' not found "
                        f"in {filename} — skipping {output_def['path']}\n"
                    )
                    manifest.append({
                        "source": filename,
                        "output": output_def["path"],
                        "section": section,
                        "status": "missing_section",
                    })
                    continue
                content = add_compile_header(extracted, filename, out_type, version)
                content = inject_toc(content, extracted, out_type)
                content = linkify_claude_paths(content, out_path, output_root)
            else:
                content = module_content

            emit(filename, out_path, content, section or "full")

        # Phase 2 — cc_rules + cc_hooks frontmatter passes
        metadata = parse_module_metadata(module_content)
        written = emit_cc_rules_for_module(
            filename, module_content, metadata, output_root, emit, version,
        )
        all_written_rules.update(written)

        for hook_entry in (metadata.get("cc_hooks") or []):
            result = collect_cc_hooks_entry(filename, hook_entry)
            if result is None:
                continue
            event, built = result
            cc_hooks_aggregate.setdefault(event, []).append(built)

    # Phase 2 — orphan cleanup for .claude/rules/kf/
    cleanup_orphan_rules(
        all_written_rules,
        output_root / ".claude/rules/kf",
        output_root,
        dry_run,
        diff_mode,
        manifest,
    )

    # Phase 2 — emit settings.kf.json (omitted entirely if hooks aggregate is empty)
    emit_settings_fragment(
        cc_hooks_aggregate, output_root, dry_run, diff_mode, manifest, version,
    )

    # Hooks — copy verbatim
    special = binding.get("special_outputs", {})
    hooks_spec = special.get("hooks", {})
    if hooks_spec and not dry_run and not diff_mode:
        hooks_dest = output_root / binding["output_structure"]["hooks_dir"]
        hooks_dest.mkdir(parents=True, exist_ok=True)
        for hook_file in hooks_spec.get("files", []):
            src = HOOKS_DIR / hook_file
            if src.exists():
                dst = hooks_dest / hook_file
                shutil.copy2(src, dst)
                manifest.append({
                    "source": f"hooks/{hook_file}",
                    "output": str((hooks_dest / hook_file).relative_to(output_root)),
                    "section": "copy",
                    "status": "written",
                    "bytes": src.stat().st_size,
                })
            else:
                sys.stderr.write(f"[kf-compile] Hook not found: {src}\n")
    elif hooks_spec:
        for hook_file in hooks_spec.get("files", []):
            manifest.append({
                "source": f"hooks/{hook_file}",
                "output": str(Path(binding["output_structure"]["hooks_dir"]) / hook_file),
                "section": "copy",
                "status": "would_write" if dry_run else "diff_skipped",
            })

    # Item C3 fail-closed -CC guard — only runs on real writes (dry_run / diff
    # don't produce on-disk artifacts to inspect).
    if not dry_run and not diff_mode:
        assert_cc_invariants(binding, output_root)

    return manifest


# Routable agents that DON'T derive from a `@delegate` token in the M00
# routing table — they are emitted bodies but never appear as @-tokens.
#   kf.md                = the orchestrator's own body (no self-delegation)
#   knowledge-librarian  = utility agent dispatched by the accretion pipeline,
#                          not by the routing table
CC_NON_ROUTABLE_AGENTS = frozenset({"kf", "knowledge-librarian"})


def assert_cc_invariants(binding: dict, output_root: Path) -> None:
    """Fail-closed -CC guard (Item C3).

    Three invariants enforced after a real write:
    (a) Every mode-agent module declared in module_outputs that emits an agent
        artifact actually produced .claude/agents/<name>.md on disk.
    (b) adversarial-critic.md contains the 'Untrusted Input Boundary' clause
        (SPEC 1 prompt-level defense — see Module 07 ## CC Agent (Adversarial
        Variant), Module 00 ## Automatic Adversarial Verification, Module 20
        verifier_tool_tier_policy).
    (c) The set of `@delegate` tokens in the orchestrator routing table
        (Module 00) is exactly the set of routable agent bodies on disk
        (.claude/agents/*.md minus CC_NON_ROUTABLE_AGENTS). No orphans either
        direction.

    Raises RuntimeError naming the failing invariant + missing artifact.
    """
    agents_dir = output_root / binding["output_structure"]["agents_dir"]

    # (a) Every declared agent output for a mode module exists on disk.
    for mod_id, mod_spec in binding.get("module_outputs", {}).items():
        for out_spec in mod_spec.get("outputs", []):
            if out_spec.get("type") != "agent":
                continue
            rel = out_spec["path"]
            target = output_root / rel
            if not target.exists():
                raise RuntimeError(
                    f"[kf-compile][-CC guard] Module '{mod_id}' declared agent "
                    f"output {rel} but no file was written. Check whether the "
                    f"module's ## {out_spec.get('section')} section exists and "
                    f"non-empty."
                )

    # (b) adversarial-critic must carry the Untrusted Input Boundary clause.
    adv = agents_dir / "adversarial-critic.md"
    if not adv.exists():
        raise RuntimeError(
            "[kf-compile][-CC guard] adversarial-critic.md missing — SPEC 1 "
            "verifier-promotion did not land. Re-author Module 07 ## CC Agent "
            "(Adversarial Variant)."
        )
    if "Untrusted Input Boundary" not in adv.read_text(encoding="utf-8"):
        raise RuntimeError(
            "[kf-compile][-CC guard] adversarial-critic.md is missing the "
            "'Untrusted Input Boundary' clause. The prompt-level defense for "
            "the adversarial verifier is required by SPEC 1; re-author the "
            "clause in Module 07 ## CC Agent (Adversarial Variant)."
        )

    # (c) Delegates ↔ routable agents bijection (no orphans).
    m00 = next(MODULES_DIR.glob("00_*.md"), None)
    if m00 is None:
        raise RuntimeError("[kf-compile][-CC guard] Module 00 not found.")
    m00_body = m00.read_text(encoding="utf-8")
    delegates = set(re.findall(r"@([a-z][a-z-]+)", m00_body))
    routable_bodies = {
        p.stem for p in agents_dir.glob("*.md")
        if p.stem not in CC_NON_ROUTABLE_AGENTS
    }
    missing_bodies = delegates - routable_bodies
    if missing_bodies:
        raise RuntimeError(
            f"[kf-compile][-CC guard] Delegate(s) in M00 routing table without "
            f"a compiled agent body: {sorted(missing_bodies)}. Either author "
            f"the ## CC Agent section in the corresponding module, or remove "
            f"the @delegate from the routing table."
        )
    orphan_bodies = routable_bodies - delegates
    if orphan_bodies:
        raise RuntimeError(
            f"[kf-compile][-CC guard] Compiled agent body without a matching "
            f"@delegate in M00 routing table: {sorted(orphan_bodies)}. Either "
            f"add the @delegate to M00 (if the agent is user-routable) or add "
            f"the agent name to CC_NON_ROUTABLE_AGENTS (utility/self body)."
        )


def strip_cc_sections(content: str) -> str:
    """
    Remove CC compilation sections from module content before writing to CP.

    Cuts the file at the first occurrence of any marker in CP_STRIP_MARKERS
    (## CC Skill / ## CC Doc / ## CC Agent / ## CC Rules / ## Section-Load Map,
    plus titled variants like '## CC Agent (Adversarial Variant)' or
    '## CC Skill — KF Fit Check'). The embed script appends CC sections at
    the end of modules so a single forward cut is sound; the Section-Load Map
    addition is defense-in-depth against canonical drift.
    """
    lines = content.split("\n")
    cut_at = len(lines)

    for i, line in enumerate(lines):
        if not line.startswith("## "):
            continue
        section_id = line[3:].strip()
        if section_id in CP_STRIP_MARKERS or any(
            section_id.startswith(m + " ") or section_id.startswith(m + " (")
            for m in CP_STRIP_MARKERS
        ):
            cut_at = i
            break

    stripped = "\n".join(lines[:cut_at]).rstrip("\n") + "\n"
    return stripped


def assert_cp_clean(out_path: Path, content: str) -> None:
    """Fail-closed -CP guard (Item B3).

    Scan content for any forbidden compilation-section heading. Raises
    RuntimeError naming the offending file + line if one slips through.
    Called from compile_claude_projects() after each file write so the
    -CP publish reliably rejects CC leakage even if strip_cc_sections
    misses a future variant.
    """
    for lineno, line in enumerate(content.split("\n"), start=1):
        if not line.startswith("## "):
            continue
        section_id = line[3:].strip()
        if section_id in CP_STRIP_MARKERS or any(
            section_id.startswith(m + " ") or section_id.startswith(m + " (")
            for m in CP_STRIP_MARKERS
        ):
            raise RuntimeError(
                f"[kf-compile][-CP guard] FORBIDDEN section leaked into "
                f"{out_path.name} at line {lineno}: '{line.rstrip()}'. "
                f"strip_cc_sections did not catch it. Fix the strip filter "
                f"before re-publishing."
            )


def compile_vscode(binding: dict, output_root: Path, dry_run: bool,
                   diff_mode: bool, version: str,
                   check_divergence: bool = False) -> list[dict]:
    """
    Compile for the vscode platform.

    VS Code uses verbatim module copy — each mode module is emitted as a
    complete .md resource file loaded at runtime by the extension host.
    Infrastructure modules (12–25) are NOT compiled; their behaviours are
    embedded in KFSession TypeScript.

    special_outputs.mode_registry is written as a JSON file.
    """
    manifest = []
    module_outputs = binding.get("module_outputs", {})
    special = binding.get("special_outputs", {})

    # --- Mode resource files ---
    for mod_id, mod_spec in module_outputs.items():
        outputs = mod_spec.get("outputs", [])
        for out_spec in outputs:
            if out_spec.get("type") != "resource":
                continue

            rel_path = out_spec["path"]
            out_path = output_root / rel_path

            # Find source module by prefix (e.g. "00" → 00_orchestrator.md)
            candidates = list(MODULES_DIR.glob(f"{mod_id}_*.md"))
            if not candidates:
                sys.stderr.write(
                    f"[kf-compile] Module '{mod_id}' not found — skipping\n"
                )
                manifest.append({
                    "source": f"{mod_id}_*.md",
                    "output": rel_path,
                    "section": "verbatim",
                    "status": "missing_module",
                })
                continue

            src = candidates[0]
            content = src.read_text(encoding="utf-8")
            entry = {
                "source": src.name,
                "output": rel_path,
                "section": "verbatim",
            }

            if diff_mode:
                existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
                if content == existing:
                    entry["status"] = "unchanged"
                else:
                    entry["status"] = "changed"
                    entry["diff_summary"] = (
                        f"{len(existing.splitlines())} → {len(content.splitlines())} lines"
                    )
            elif dry_run:
                entry["status"] = "would_write"
            else:
                if check_divergence:
                    reason = detect_divergence(out_path, content)
                    if reason:
                        entry["status"] = "diverged"
                        entry["diverged_reason"] = reason
                        entry["bytes"] = len(content.encode())
                        manifest.append(entry)
                        continue
                out_path.parent.mkdir(parents=True, exist_ok=True)
                out_path.write_text(content, encoding="utf-8")
                entry["status"] = "written"

            entry["bytes"] = len(content.encode())
            manifest.append(entry)

    # --- special_outputs.mode_registry ---
    registry_spec = special.get("mode_registry", {})
    if registry_spec:
        reg_path = output_root / registry_spec["path"]
        reg_content = registry_spec.get("content", "")
        entry = {
            "source": "platform-bindings/vscode.yaml",
            "output": registry_spec["path"],
            "section": "mode_registry",
        }

        if diff_mode:
            existing = reg_path.read_text(encoding="utf-8") if reg_path.exists() else ""
            entry["status"] = "unchanged" if reg_content.strip() == existing.strip() else "changed"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            normalized = reg_content.strip() + "\n"
            if check_divergence:
                reason = detect_divergence(reg_path, normalized)
                if reason:
                    entry["status"] = "diverged"
                    entry["diverged_reason"] = reason
                    entry["bytes"] = len(reg_content.encode())
                    manifest.append(entry)
                    return manifest
            reg_path.parent.mkdir(parents=True, exist_ok=True)
            reg_path.write_text(normalized, encoding="utf-8")
            entry["status"] = "written"

        entry["bytes"] = len(reg_content.encode())
        manifest.append(entry)

    return manifest


# ---------------------------------------------------------------------------
# Plugin bundle compiler (SPEC 5)
# ---------------------------------------------------------------------------

_SEMVER_RE = re.compile(r"^\s*(\d+)\.(\d+)\.(\d+)")


def _parse_semver(s: str) -> tuple[int, int, int] | None:
    """Parse a semver string to a (major, minor, patch) tuple.

    Returns None if the string doesn't match major.minor.patch. Only the
    leading numeric triple is used; pre-release/build suffixes are ignored.
    """
    if not s:
        return None
    m = _SEMVER_RE.match(str(s))
    if not m:
        return None
    return (int(m.group(1)), int(m.group(2)), int(m.group(3)))


def _semver_satisfies(module_version: str, required: str) -> bool:
    """Return True if `module_version` satisfies a `>=X.Y.Z` constraint.

    SPEC 5 only uses the `>=` form for `requires_module_version`. This helper
    intentionally implements that subset and refuses other operators (they
    return False, surfacing a parsable-but-unmet gate rather than crashing).
    """
    req = required.strip()
    if not req.startswith(">="):
        return False
    floor = _parse_semver(req[2:])
    have = _parse_semver(module_version)
    if floor is None or have is None:
        return False
    return have >= floor


def _bundle_version_stamp(out_type: str, name: str, bundle_version: str,
                           source_module: str, module_version: str) -> str:
    """Build the kf-bundle HTML-comment header (SPEC 5 D2b).

    Format:
      <!-- kf-bundle: skill=builder | bundle_version=1.2.3 | source_module=02_builder.md | module_version=7.4.0 -->
    """
    return (
        f"<!-- kf-bundle: {out_type}={name} | bundle_version={bundle_version} | "
        f"source_module={source_module} | module_version={module_version} -->\n"
    )


def compile_plugin_bundle(binding: dict, output_root: Path, dry_run: bool,
                           diff_mode: bool, version: str,
                           check_divergence: bool = False) -> list[dict]:
    """
    Compile for the plugin-bundle target (SPEC 5).

    Emits a self-contained installable bundle at output_root:
      kf-plugin-bundle.json   bundle manifest
      skills/                 compiled skill files (kf-compile + kf-bundle stamps)
      agents/                 compiled agent files (kf-compile + kf-bundle stamps)
      mcp/                    connector descriptors (path-validated at install)
      install.sh              consumer-side installer (from .tmpl + version stamp)

    `requires_module_version` is a per-output semver gate (D2): when the
    source module's version is below the floor, the manifest entry shows
    `status: skipped_version_gate` and no file is written. Used for outputs
    that depend on module sections not yet shipped (e.g., adversarial-critic
    depends on SPEC 1 land of Module 07 ≥ 7.5.0).

    bundle_version is currently pinned to the kf.yaml system version (D2b).
    Future composition-only bumps may decouple this.

    Decision-tag: evaluative (parallels existing compile_claude_code patterns;
    extends them with semver gating + bundle-version stamping).
    """
    manifest: list[dict] = []
    bundle_version = version  # at v1, bundle version tracks kf.yaml version

    # Output structure paths (from binding) — bundle-relative
    out_struct = binding.get("output_structure", {})
    skills_dirname = out_struct.get("skills_dir", "skills/").rstrip("/")
    agents_dirname = out_struct.get("agents_dir", "agents/").rstrip("/")
    mcp_dirname = out_struct.get("mcp_dir", "mcp/").rstrip("/")
    manifest_filename = out_struct.get("manifest_path", "kf-plugin-bundle.json")
    installer_filename = out_struct.get("installer_path", "install.sh")

    def emit_bundle_file(source: str, out_path: Path, content: str, section: str,
                          extra: dict | None = None) -> None:
        entry = {
            "source": source,
            "output": str(out_path.relative_to(output_root)),
            "section": section,
        }
        if extra:
            entry.update(extra)
        if diff_mode:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            entry["status"] = "unchanged" if content == existing else "changed"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            if check_divergence:
                reason = detect_divergence(out_path, content)
                if reason:
                    entry["status"] = "diverged"
                    entry["diverged_reason"] = reason
                    entry["bytes"] = len(content.encode())
                    manifest.append(entry)
                    return
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            entry["status"] = "written"
        entry["bytes"] = len(content.encode())
        manifest.append(entry)

    # ----- Per-module outputs (skills + agents) -----
    module_outputs = binding.get("module_outputs", {})
    for module_num, module_spec in module_outputs.items():
        filename, module_content = load_module(module_num)
        if module_content is None:
            sys.stderr.write(
                f"[kf-compile] Module {module_num} not found — skipping\n"
            )
            continue

        # Extract module version from metadata block for stamps + gates
        metadata = parse_module_metadata(module_content)
        module_meta = metadata.get("module") if isinstance(metadata, dict) else None
        module_version_str = ""
        if isinstance(module_meta, dict):
            module_version_str = str(module_meta.get("version", "")).strip()

        for output_def in module_spec.get("outputs", []):
            out_type = output_def["type"]                  # "skill" | "agent"
            out_rel = output_def["path"]                   # e.g. "agents/builder.md"
            section = output_def.get("section")
            requires = output_def.get("requires_module_version")
            out_path = output_root / out_rel

            # ---- Version gate (D2) ----
            if requires and not _semver_satisfies(module_version_str, requires):
                manifest.append({
                    "source": filename,
                    "output": out_rel,
                    "section": section or "full",
                    "status": "skipped_version_gate",
                    "requires_module_version": requires,
                    "module_version": module_version_str,
                })
                continue

            # ---- Section extraction ----
            extracted = extract_section(module_content, section) if section else module_content
            if section and extracted is None:
                sys.stderr.write(
                    f"[kf-compile] WARNING: section '## {section}' not found "
                    f"in {filename} — skipping {out_rel}\n"
                )
                manifest.append({
                    "source": filename,
                    "output": out_rel,
                    "section": section,
                    "status": "missing_section",
                })
                continue

            # ---- Stamp: kf-compile sentinel + kf-bundle stamp ----
            content = add_compile_header(extracted, filename, out_type, version)
            # Derive a short name from out_rel for the stamp (e.g., "builder")
            name = Path(out_rel).stem
            stamp = _bundle_version_stamp(out_type, name, bundle_version,
                                           filename, module_version_str or "unknown")
            # Insert stamp on the second line so kf-compile header stays at line 1
            header_line, body = content.split("\n", 1)
            content = f"{header_line}\n{stamp}{body}"

            emit_bundle_file(
                filename, out_path, content, section or "full",
                extra={"module_version": module_version_str,
                       "bundle_version": bundle_version},
            )

    # ----- MCP connectors -----
    # Compiler writes a small descriptor per connector into mcp/ describing
    # how the installer should resolve the connector. The actual server JSON
    # is loaded at install time (per D3b path_type discipline).
    mcp_connectors = binding.get("mcp_connectors", []) or []
    for connector in mcp_connectors:
        cid = connector.get("id", "<unknown>")
        descriptor_path = output_root / mcp_dirname / f"{cid}.json"
        descriptor = {
            "id": cid,
            "path_type": connector.get("path_type", "bundled"),
            "source": connector.get("source"),
            "source_path": connector.get("source_path"),
            "bundle_path": connector.get("bundle_path"),
            "fallback_message": connector.get("fallback_message", ""),
            "targets": connector.get("targets", []),
            "required": bool(connector.get("required", False)),
        }
        # Strip Nones for a cleaner descriptor
        descriptor = {k: v for k, v in descriptor.items() if v is not None}
        descriptor_content = json.dumps(descriptor, indent=2) + "\n"
        emit_bundle_file(
            f"platform-bindings/plugin-bundle.yaml#mcp:{cid}",
            descriptor_path,
            descriptor_content,
            "mcp_descriptor",
        )

    # ----- Installer (install.sh) from template -----
    consumer_installer = binding.get("consumer_installer", {}) or {}
    template_rel = consumer_installer.get("template")
    if template_rel:
        template_path = CORE_ROOT / template_rel
        if template_path.exists():
            template_content = template_path.read_text(encoding="utf-8")
            installed_at = datetime.now(timezone.utc).isoformat()
            installer_content = (
                template_content
                .replace("{{BUNDLE_VERSION}}", bundle_version)
                .replace("{{BUNDLE_TIMESTAMP}}", installed_at)
            )
            installer_path = output_root / installer_filename
            emit_bundle_file(
                template_rel,
                installer_path,
                installer_content,
                "installer_template",
            )
            # chmod +x for real writes (best-effort; ignore on filesystems
            # without exec bit semantics).
            if not dry_run and not diff_mode and installer_path.exists():
                try:
                    installer_path.chmod(0o755)
                except OSError:
                    pass
        else:
            sys.stderr.write(
                f"[kf-compile] Installer template not found: {template_path}\n"
            )

    # ----- Bundle manifest (kf-plugin-bundle.json) -----
    # Distinct from .kf-compile-manifest.json: this is the install-time
    # contract that install.sh reads (skills, agents, mcp_connectors).
    skills_entries = []
    agents_entries = []
    for entry in manifest:
        section = entry.get("section", "")
        if section == "mcp_descriptor" or section == "installer_template":
            continue
        out_rel = entry.get("output", "")
        name = Path(out_rel).stem if out_rel else ""
        is_skill = out_rel.startswith(skills_dirname + "/")
        is_agent = out_rel.startswith(agents_dirname + "/")
        if not (is_skill or is_agent):
            continue
        target = skills_entries if is_skill else agents_entries
        target.append({
            "name": name,
            "path": out_rel,
            "module_source": entry.get("source", ""),
            "module_version": entry.get("module_version", ""),
            "status": entry.get("status", ""),
            **({"requires_module_version": entry["requires_module_version"]}
               if "requires_module_version" in entry else {}),
        })

    bundle_manifest = {
        "version": version,
        "bundle_id": "kf-plugin-bundle",
        "bundle_version": bundle_version,
        "compiled_at": datetime.now(timezone.utc).isoformat(),
        "source": "knowledgeforge-core",
        "skills": skills_entries,
        "agents": agents_entries,
        "mcp_connectors": mcp_connectors,
        "install_protocol": [
            {"step": "copy_skills_to_target_repo"},
            {"step": "copy_agents_to_target_repo"},
            {"step": "register_mcp_connectors_in_target_settings"},
            {"step": "emit_install_receipt"},
        ],
    }
    manifest_content = json.dumps(bundle_manifest, indent=2) + "\n"
    emit_bundle_file(
        "kf-compile.py#compile_plugin_bundle",
        output_root / manifest_filename,
        manifest_content,
        "bundle_manifest",
    )

    return manifest


def compile_codex_placeholder(binding: dict, output_root: Path, dry_run: bool,
                               diff_mode: bool, version: str,
                               check_divergence: bool = False) -> list[dict]:
    """
    Codex target — DEFERRED placeholder (SPEC 1 D7).

    The Codex agent schema (TOML) authoritative reference is not yet in core,
    so we cannot emit valid agent files. This handler writes nothing and
    returns an empty manifest with a stderr warning. Recommended exit code 0
    so CI dry-runs and inventory scans don't false-fail on a known-deferred
    target.

    When the binding's `status` field flips from "deferred" to "active" AND
    `module_outputs` becomes non-empty, this function will be replaced by a
    real compile_codex(...) that mirrors compile_claude_code(...) but emits
    TOML instead of markdown.

    Decision-tag: evaluative (parallels existing compile_* dispatch shape;
    writes no files but returns the expected list[dict] manifest type).
    """
    status = (binding or {}).get("status", "unknown")
    sys.stderr.write(
        "[kf-compile] Codex target is deferred "
        "(see platform-bindings/codex.yaml). Bind schema then re-run. "
        f"(binding status: {status})\n"
    )
    return []


def compile_claude_projects(binding: dict, output_root: Path, dry_run: bool,
                              diff_mode: bool, version: str,
                              check_divergence: bool = False) -> list[dict]:
    """
    Compile for the claude-projects platform.

    CP uses full module content with CC compilation sections stripped,
    and CP filename mapping applied.
    """
    manifest = []
    filename_map = binding.get("filename_map", {})

    for core_name, cp_name in filename_map.items():
        # Find source module
        src = MODULES_DIR / core_name
        if not src.exists():
            sys.stderr.write(f"[kf-compile] Module not found: {core_name} — skipping\n")
            continue

        content = strip_cc_sections(src.read_text(encoding="utf-8"))
        out_path = output_root / cp_name
        # Item B3 fail-closed -CP guard — never silently publish a leak.
        assert_cp_clean(out_path, content)

        entry = {"source": core_name, "output": cp_name, "section": "full"}

        if diff_mode:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if content == existing:
                entry["status"] = "unchanged"
            else:
                entry["status"] = "changed"
                old_lines = len(existing.splitlines())
                new_lines = len(content.splitlines())
                entry["diff_summary"] = f"{old_lines} → {new_lines} lines"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            if check_divergence:
                reason = detect_divergence(out_path, content)
                if reason:
                    entry["status"] = "diverged"
                    entry["diverged_reason"] = reason
                    entry["bytes"] = len(content.encode())
                    manifest.append(entry)
                    continue
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            entry["status"] = "written"

        entry["bytes"] = len(content.encode())
        manifest.append(entry)

    return manifest


# ---------------------------------------------------------------------------
# Manifest reporting
# ---------------------------------------------------------------------------

def print_manifest(manifest: list[dict], platform: str, dry_run: bool, diff_mode: bool):
    mode = "DRY RUN" if dry_run else ("DIFF" if diff_mode else "COMPILE")
    print(f"\nkf-compile [{mode}] → {platform}")
    print("=" * 60)

    counts = {"written": 0, "unchanged": 0, "changed": 0,
              "would_write": 0, "missing_section": 0}

    for entry in manifest:
        status = entry["status"]
        counts[status] = counts.get(status, 0) + 1

        if status == "unchanged":
            marker = "  ·"
        elif status in ("written", "would_write"):
            marker = "  +"
        elif status == "changed":
            marker = "  ~"
        elif status == "missing_section":
            marker = "  !"
        elif status == "diverged":
            marker = "  ⚠"
        else:
            marker = "  ?"

        line = f"{marker} {entry['output']}"
        if "diff_summary" in entry:
            line += f"  ({entry['diff_summary']})"
        if status == "missing_section":
            line += f"  ← MISSING section '## {entry['section']}' in {entry['source']}"
        if status == "diverged":
            line += f"  ← DIVERGED: {entry.get('diverged_reason', 'hand-edited')}"
        print(line)

    print("=" * 60)
    if dry_run:
        print(f"Would write: {counts.get('would_write', 0)}  "
              f"Skipped (missing section): {counts.get('missing_section', 0)}")
    elif diff_mode:
        print(f"Changed: {counts.get('changed', 0)}  "
              f"Unchanged: {counts.get('unchanged', 0)}  "
              f"Missing section: {counts.get('missing_section', 0)}")
    else:
        print(f"Written: {counts.get('written', 0)}  "
              f"Skipped (missing section): {counts.get('missing_section', 0)}  "
              f"Diverged (skipped): {counts.get('diverged', 0)}")


def _section_anchor(section: str) -> str:
    """Convert a section heading to a GitHub markdown anchor.

    '## CC Skill' → '#cc-skill'  (lowercase, spaces→hyphens, strip punctuation)
    """
    anchor = section.lower().replace(" ", "-")
    # GitHub strips most punctuation except hyphens and underscores
    anchor = re.sub(r"[^\w\-]", "", anchor)
    return f"#{anchor}"


def write_manifest(manifest: list[dict], output_root: Path, platform: str, version: str):
    """Write compilation manifest.

    - JSON → variant repo (machine-readable, tracked there)
    - MD load map → knowledgeforge-core root (human-navigable on GitHub)

    The MD lives in core so that relative links like `modules/02_builder.md#cc-skill`
    resolve correctly within the same GitHub repo. Cross-repo relative links don't
    work on GitHub, so the map must be co-located with the source modules.
    """
    ts = datetime.now(timezone.utc).isoformat()

    # --- JSON (machine-readable) → variant repo ---
    manifest_path = output_root / ".kf-compile-manifest.json"
    data = {
        "compiled_at": ts,
        "source": "knowledgeforge-core",
        "platform": platform,
        "version": version,
        "entries": manifest,
    }
    manifest_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # --- Markdown load map (human-navigable) → core repo root ---
    # Links are relative to CORE_ROOT, so `modules/02_builder.md#cc-skill`
    # resolves on GitHub without any path gymnastics.
    # Deterministic load map: no timestamp embedded (was causing load-map-*.md
    # to show as modified on every compile even when no content changed —
    # noop git churn in core. The authoritative compiled_at lives in
    # .kf-compile-manifest.json in each variant repo). bead `rxc`.
    md_lines = [
        f"# KnowledgeForge Load Map — `{platform}`",
        f"",
        f"**Version:** `{version}`",
        f"",
        f"Each row shows one compiled output and the exact source section it was extracted from.",
        f"Click the source link to jump directly to that section in the module file.",
        f"",
        f"| Status | Output (variant repo) | Source module | Section |",
        f"|:---:|---|---|:---:|",
    ]

    for entry in manifest:
        status = entry.get("status", "")
        source = entry.get("source", "")
        section = entry.get("section", "full")
        output = entry.get("output", "")

        # Source link — relative from core repo root, GitHub resolves these natively.
        if section not in ("full", "copy") and source:
            anchor = _section_anchor(section)
            source_link = f"[`{source}`](modules/{source}{anchor})"
            section_label = f"`{section}`"
        elif section == "copy":
            source_link = f"`{source}`"
            section_label = "_verbatim_"
        else:
            source_link = f"[`{source}`](modules/{source})" if source else "—"
            section_label = "_full file_"

        badge = {
            "written": "✓", "unchanged": "·", "changed": "~",
            "missing_section": "⚠︎", "would_write": "?",
        }.get(status, status)

        output_cell = f"`{output}`" if output else "—"
        md_lines.append(f"| {badge} | {output_cell} | {source_link} | {section_label} |")

    md_lines += [
        "",
        "---",
        f"_Generated by `compiler/kf-compile.py`. Do not edit manually._",
        f"_JSON manifest (machine-readable) is at `.kf-compile-manifest.json` in the variant repo._",
    ]

    # Write to core root so relative links resolve on GitHub.
    # Named without a dot prefix so it's visible in GitHub's file listing.
    md_path = CORE_ROOT / f"load-map-{platform}.md"
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    print(f"Manifest written:  {manifest_path}")
    print(f"Load map written:  {md_path}")


# ---------------------------------------------------------------------------
# Version loader
# ---------------------------------------------------------------------------

def load_version() -> str:
    kf_yaml = CORE_ROOT / "kf.yaml"
    if kf_yaml.exists():
        with open(kf_yaml, encoding="utf-8") as f:
            data = yaml.safe_load(f)
            return str(data.get("version", "unknown"))
    return "unknown"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="KnowledgeForge compiler — core modules → variant repos"
    )
    parser.add_argument(
        "--target",
        required=True,
        choices=["claude-code", "claude-projects", "vscode", "plugin-bundle", "codex"],
        help="Platform target to compile for",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to the target variant repo root",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be written without writing",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Show what has changed vs. current output repo (no writes)",
    )
    parser.add_argument(
        "--manifest",
        action="store_true",
        default=True,
        help="Write .kf-compile-manifest.json to output repo (default: true)",
    )
    parser.add_argument(
        "--check-divergence",
        action="store_true",
        help=(
            "Refuse to overwrite target files whose content differs from what the "
            "current compile would produce (compile-header timestamp drift ignored). "
            "Catches the case where a target file was hand-edited and the edits were "
            "never back-ported to core. Diverged files are skipped, not aborted; the "
            "process exits non-zero if any divergence was detected."
        ),
    )
    args = parser.parse_args()

    if args.dry_run and args.diff:
        sys.stderr.write("[kf-compile] --dry-run and --diff are mutually exclusive\n")
        sys.exit(1)
    if args.check_divergence and (args.dry_run or args.diff):
        sys.stderr.write(
            "[kf-compile] --check-divergence applies only to real writes "
            "(incompatible with --dry-run / --diff)\n"
        )
        sys.exit(1)

    output_root = Path(args.output).resolve()
    if not output_root.exists():
        sys.stderr.write(f"[kf-compile] Output directory not found: {output_root}\n")
        sys.exit(2)

    version = load_version()
    binding = load_binding(args.target)

    if args.target == "claude-code":
        manifest = compile_claude_code(
            binding, output_root, args.dry_run, args.diff, version,
            check_divergence=args.check_divergence,
        )
    elif args.target == "claude-projects":
        manifest = compile_claude_projects(
            binding, output_root, args.dry_run, args.diff, version,
            check_divergence=args.check_divergence,
        )
    elif args.target == "vscode":
        manifest = compile_vscode(
            binding, output_root, args.dry_run, args.diff, version,
            check_divergence=args.check_divergence,
        )
    elif args.target == "plugin-bundle":
        manifest = compile_plugin_bundle(
            binding, output_root, args.dry_run, args.diff, version,
            check_divergence=args.check_divergence,
        )
    elif args.target == "codex":
        # SPEC 1 D7 — Codex binding is deferred; placeholder emits no files,
        # writes a stderr warning, and exits 0 so CI/dry-runs don't false-fail.
        manifest = compile_codex_placeholder(
            binding, output_root, args.dry_run, args.diff, version,
            check_divergence=args.check_divergence,
        )
    else:
        sys.stderr.write(f"[kf-compile] Target '{args.target}' not yet implemented\n")
        sys.exit(1)

    print_manifest(manifest, args.target, args.dry_run, args.diff)

    if not args.dry_run and not args.diff and args.manifest:
        write_manifest(manifest, output_root, args.target, version)

    # Exit 1 if any sections were missing (signals incomplete module annotations)
    missing = sum(1 for e in manifest if e["status"] == "missing_section")
    if missing:
        sys.stderr.write(
            f"\n[kf-compile] {missing} output(s) skipped due to missing sections.\n"
            f"Add '## CC Skill' / '## CC Doc' / '## CC Agent' sections to modules.\n"
        )
        sys.exit(1)

    # Exit 2 if --check-divergence detected hand-edited target files.
    # Distinct exit code from missing_section so callers can tell them apart.
    diverged = [e for e in manifest if e.get("status") == "diverged"]
    if diverged:
        sys.stderr.write(
            f"\n[kf-compile] {len(diverged)} output(s) skipped — target has been hand-edited.\n"
            f"Back-port the changes to core/modules/, then re-run compile.\n"
        )
        for e in diverged:
            sys.stderr.write(
                f"  • {e['output']}  ({e.get('diverged_reason', 'unknown')})\n"
            )
        sys.exit(2)


if __name__ == "__main__":
    main()
