#!/usr/bin/env python3
"""
kf-compile.py — KnowledgeForge compiler.

Reads canonical module specs from knowledgeforge-core/modules/, applies
platform bindings, and writes compiled output to a target variant repo.

Usage:
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo
    python3 compiler/kf-compile.py --target claude-projects --output /path/to/cp-repo
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo --dry-run
    python3 compiler/kf-compile.py --target claude-code --output /path/to/cc-repo --diff

Exit codes:
    0 — success
    1 — binding/module errors
    2 — output write errors
"""

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("[kf-compile] PyYAML required: pip install pyyaml\n")
    sys.exit(1)

# Resolve paths relative to this script (works regardless of cwd)
CORE_ROOT = Path(__file__).parent.parent
MODULES_DIR = CORE_ROOT / "modules"
BINDINGS_DIR = CORE_ROOT / "platform-bindings"
HOOKS_DIR = CORE_ROOT / "hooks"


# ---------------------------------------------------------------------------
# Section extraction
# ---------------------------------------------------------------------------


# Section names that delimit compilation blocks. The extractor only stops
# when it hits another CC marker — internal ## headings in embedded content
# are passed through unchanged.
CC_SECTION_MARKERS = frozenset({"CC Skill", "CC Doc", "CC Agent", "CC Rules"})


def extract_section(content: str, section_name: str) -> str | None:
    """
    Extract everything between '## {section_name}' and the next CC section marker.

    Stops only on '## CC Skill', '## CC Doc', '## CC Agent', '## CC Rules' —
    NOT on arbitrary ## headings inside the embedded content.

    Returns None if the section is not found.
    Strips leading/trailing whitespace from the extracted block.
    """
    lines = content.split("\n")
    in_section = False
    result = []

    for line in lines:
        stripped = line.strip()
        if stripped == f"## {section_name}":
            in_section = True
            continue
        if in_section:
            # Stop only at another CC section marker, not regular headings
            if line.startswith("## ") and line[3:].strip() in CC_SECTION_MARKERS:
                break
            result.append(line)

    if not in_section:
        return None

    return "\n".join(result).strip()


def add_compile_header(content: str, source_module: str, output_type: str,
                        version: str) -> str:
    """Prepend a small compilation metadata comment to generated files."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        f"<!-- Generated by kf-compile | source: {source_module} "
        f"| type: {output_type} | version: {version} | compiled: {ts} -->\n"
    )
    return header + content


def heading_to_anchor(text: str) -> str:
    """Convert a markdown heading to a GitHub-compatible anchor.

    GitHub's algorithm: lowercase, strip all non-alphanumeric/space/hyphen chars,
    replace spaces with hyphens, collapse runs of hyphens.

    '## Full PDIA Method'  → '#full-pdia-method'
    '## Bias Detection'    → '#bias-detection'
    '## When to Calibrate' → '#when-to-calibrate'
    """
    anchor = text.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)   # strip punctuation except hyphens
    anchor = re.sub(r"\s+", "-", anchor)        # spaces → hyphens
    anchor = re.sub(r"-{2,}", "-", anchor)      # collapse multiple hyphens
    return "#" + anchor.strip("-")


def generate_section_toc(content: str, min_headings: int = 2) -> str | None:
    """Generate a compact inline TOC from ## headings in extracted content.

    Returns a markdown line like:
        **Sections:** [When to Calibrate](#when-to-calibrate) · [Multi-Run Protocol](#multi-run-protocol)

    Returns None when fewer than min_headings ## headings are found (no point
    generating a TOC for a single-section file).

    Only indexes ## level — # (title) and ### (sub-items) are excluded.

    Headings containing '→' (navigation hints, file path references) have the
    path part stripped for display: 'Section-Load Map → ~/.claude/...' becomes
    'Section-Load Map' in the TOC link, anchored to the cleaned text.
    """
    headings = []
    for line in content.split("\n"):
        if line.startswith("## "):
            text = line[3:].strip()
            if not text:
                continue
            # Strip ' → path' suffixes — use only the label before the arrow
            display = text.split("→")[0].strip() if "→" in text else text
            headings.append((display, heading_to_anchor(display)))

    if len(headings) < min_headings:
        return None

    links = " · ".join(f"[{display}]({anchor})" for display, anchor in headings)
    return f"**Sections:** {links}"


def inject_toc(compiled_content: str, raw_content: str, out_type: str) -> str:
    """Inject a section TOC into compiled content after the compile header.

    Only fires for doc/skill/agent types with 2+ ## headings.
    Rules and verbatim copies are left unchanged.

    Placement:
    - Doc/Skill: TOC immediately after the compile header comment.
    - Agent: TOC after the YAML frontmatter block (--- ... ---) so the
      frontmatter stays machine-parseable at file top.
    """
    if out_type not in ("doc", "skill", "agent"):
        return compiled_content

    toc = generate_section_toc(raw_content)
    if toc is None:
        return compiled_content

    # compiled_content = "<!-- header -->\n{body}"
    header_line, body = compiled_content.split("\n", 1)

    if out_type == "agent":
        # Agent files have YAML frontmatter: ---\n...\n---\n
        # Inject TOC after the closing --- so frontmatter stays intact.
        body_stripped = body.lstrip("\n")
        if body_stripped.startswith("---\n"):
            closing = body_stripped.find("\n---\n", 4)
            if closing != -1:
                frontmatter = body_stripped[: closing + 5]   # up to and including ---\n
                rest = body_stripped[closing + 5 :]
                return f"{header_line}\n{frontmatter}\n{toc}\n\n---\n{rest}"
        # No frontmatter found — fall through to default placement

    return f"{header_line}\n\n{toc}\n\n---\n{body}"


def linkify_claude_paths(content: str, out_path: Path, output_root: Path) -> str:
    """Convert `~/.claude/path.md` references in Section-Load Maps to relative links.

    Maps `~/.claude/` → `{output_root}/.claude/` then computes a relative path
    from out_path's parent directory to the referenced file.

    Pattern forms handled:
      `~/.claude/X.md`              → [X.md](relative/X.md)
      `~/.claude/X.md` → Section   → [X.md#section-anchor](relative/X.md#section-anchor)

    The regex only matches backtick-delimited `~/.claude/` paths so false
    positives outside Section-Load Map blocks are negligible.
    """
    claude_root = output_root / ".claude"
    out_dir = out_path.parent

    def replace_path(match: re.Match) -> str:
        path_part = match.group(1)      # e.g., "skills/kf/builder.md"
        section_hint = match.group(2)   # e.g., "Builder accretion section" or None

        # Map ~/.claude/X → absolute target in variant repo
        abs_target = claude_root / path_part

        # Relative path from output file's directory to the target
        try:
            rel = Path(os.path.relpath(abs_target, out_dir)).as_posix()
        except ValueError:
            # Different drive on Windows — return original unchanged
            return match.group(0)

        display = Path(path_part).name

        anchor = ""
        if section_hint:
            anchor = heading_to_anchor(section_hint.strip())

        return f"[{display}]({rel}{anchor})"

    # Match: `~/.claude/{path.md}` optionally followed by ` → {section text}`
    # group 1: path after ~/.claude/
    # group 2: optional section name after →  (to end of line, non-greedy)
    pattern = r'`~/\.claude/([^`]+\.md)`(?:\s*→\s*([^\n`]+?))?(?=\s*\n|\s*$)'

    return re.sub(pattern, replace_path, content, flags=re.MULTILINE)


# ---------------------------------------------------------------------------
# Module loader
# ---------------------------------------------------------------------------

def load_module(module_num: str) -> tuple[str, str] | tuple[None, None]:
    """
    Load a module file by two-digit prefix number.

    Returns (filename, content) or (None, None) if not found.
    """
    pattern = f"{module_num}_*.md"
    matches = list(MODULES_DIR.glob(pattern))
    if not matches:
        return None, None
    return matches[0].name, matches[0].read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Platform binding loader
# ---------------------------------------------------------------------------

def load_binding(target: str) -> dict:
    binding_path = BINDINGS_DIR / f"{target}.yaml"
    if not binding_path.exists():
        sys.stderr.write(f"[kf-compile] Binding not found: {binding_path}\n")
        sys.exit(1)
    with open(binding_path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Compilers per platform
# ---------------------------------------------------------------------------

def compile_claude_code(binding: dict, output_root: Path, dry_run: bool,
                         diff_mode: bool, version: str) -> list[dict]:
    """
    Compile for the claude-code platform.

    Returns a manifest list: [{source, output, section, status, bytes}]
    """
    manifest = []

    def emit(source: str, out_path: Path, content: str, section: str):
        entry = {"source": source, "output": str(out_path.relative_to(output_root)),
                 "section": section}
        if diff_mode:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if content == existing:
                entry["status"] = "unchanged"
            else:
                entry["status"] = "changed"
                # Show a small diff summary
                old_lines = len(existing.splitlines())
                new_lines = len(content.splitlines())
                entry["diff_summary"] = f"{old_lines} → {new_lines} lines"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            entry["status"] = "written"
        entry["bytes"] = len(content.encode())
        manifest.append(entry)

    module_outputs = binding.get("module_outputs", {})

    for module_num, module_spec in module_outputs.items():
        filename, module_content = load_module(module_num)
        if module_content is None:
            sys.stderr.write(f"[kf-compile] Module {module_num} not found — skipping\n")
            continue

        for output_def in module_spec.get("outputs", []):
            out_type = output_def["type"]
            out_path = output_root / output_def["path"]
            section = output_def.get("section")

            if section:
                extracted = extract_section(module_content, section)
                if extracted is None:
                    sys.stderr.write(
                        f"[kf-compile] WARNING: section '## {section}' not found "
                        f"in {filename} — skipping {output_def['path']}\n"
                    )
                    manifest.append({
                        "source": filename,
                        "output": output_def["path"],
                        "section": section,
                        "status": "missing_section",
                    })
                    continue
                content = add_compile_header(extracted, filename, out_type, version)
                content = inject_toc(content, extracted, out_type)
                content = linkify_claude_paths(content, out_path, output_root)
            else:
                content = module_content

            emit(filename, out_path, content, section or "full")

    # Hooks — copy verbatim
    special = binding.get("special_outputs", {})
    hooks_spec = special.get("hooks", {})
    if hooks_spec and not dry_run and not diff_mode:
        hooks_dest = output_root / binding["output_structure"]["hooks_dir"]
        hooks_dest.mkdir(parents=True, exist_ok=True)
        for hook_file in hooks_spec.get("files", []):
            src = HOOKS_DIR / hook_file
            if src.exists():
                dst = hooks_dest / hook_file
                shutil.copy2(src, dst)
                manifest.append({
                    "source": f"hooks/{hook_file}",
                    "output": str((hooks_dest / hook_file).relative_to(output_root)),
                    "section": "copy",
                    "status": "written",
                    "bytes": src.stat().st_size,
                })
            else:
                sys.stderr.write(f"[kf-compile] Hook not found: {src}\n")
    elif hooks_spec:
        for hook_file in hooks_spec.get("files", []):
            manifest.append({
                "source": f"hooks/{hook_file}",
                "output": str(Path(binding["output_structure"]["hooks_dir"]) / hook_file),
                "section": "copy",
                "status": "would_write" if dry_run else "diff_skipped",
            })

    return manifest


def strip_cc_sections(content: str) -> str:
    """
    Remove CC compilation sections from module content before writing to CP.

    The embed script always appends CC sections at the end of modules, so
    everything from the first ## CC * marker to EOF is compilation content.
    Strip it entirely — CP gets clean module content without compilation anchors.
    """
    lines = content.split("\n")
    cut_at = len(lines)

    for i, line in enumerate(lines):
        if line.startswith("## ") and line[3:].strip() in CC_SECTION_MARKERS:
            cut_at = i
            break

    stripped = "\n".join(lines[:cut_at]).rstrip("\n") + "\n"
    return stripped


def compile_claude_projects(binding: dict, output_root: Path, dry_run: bool,
                              diff_mode: bool, version: str) -> list[dict]:
    """
    Compile for the claude-projects platform.

    CP uses full module content with CC compilation sections stripped,
    and CP filename mapping applied.
    """
    manifest = []
    filename_map = binding.get("filename_map", {})

    for core_name, cp_name in filename_map.items():
        # Find source module
        src = MODULES_DIR / core_name
        if not src.exists():
            sys.stderr.write(f"[kf-compile] Module not found: {core_name} — skipping\n")
            continue

        content = strip_cc_sections(src.read_text(encoding="utf-8"))
        out_path = output_root / cp_name

        entry = {"source": core_name, "output": cp_name, "section": "full"}

        if diff_mode:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if content == existing:
                entry["status"] = "unchanged"
            else:
                entry["status"] = "changed"
                old_lines = len(existing.splitlines())
                new_lines = len(content.splitlines())
                entry["diff_summary"] = f"{old_lines} → {new_lines} lines"
        elif dry_run:
            entry["status"] = "would_write"
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            entry["status"] = "written"

        entry["bytes"] = len(content.encode())
        manifest.append(entry)

    return manifest


# ---------------------------------------------------------------------------
# Manifest reporting
# ---------------------------------------------------------------------------

def print_manifest(manifest: list[dict], platform: str, dry_run: bool, diff_mode: bool):
    mode = "DRY RUN" if dry_run else ("DIFF" if diff_mode else "COMPILE")
    print(f"\nkf-compile [{mode}] → {platform}")
    print("=" * 60)

    counts = {"written": 0, "unchanged": 0, "changed": 0,
              "would_write": 0, "missing_section": 0}

    for entry in manifest:
        status = entry["status"]
        counts[status] = counts.get(status, 0) + 1

        if status == "unchanged":
            marker = "  ·"
        elif status in ("written", "would_write"):
            marker = "  +"
        elif status == "changed":
            marker = "  ~"
        elif status == "missing_section":
            marker = "  !"
        else:
            marker = "  ?"

        line = f"{marker} {entry['output']}"
        if "diff_summary" in entry:
            line += f"  ({entry['diff_summary']})"
        if status == "missing_section":
            line += f"  ← MISSING section '## {entry['section']}' in {entry['source']}"
        print(line)

    print("=" * 60)
    if dry_run:
        print(f"Would write: {counts.get('would_write', 0)}  "
              f"Skipped (missing section): {counts.get('missing_section', 0)}")
    elif diff_mode:
        print(f"Changed: {counts.get('changed', 0)}  "
              f"Unchanged: {counts.get('unchanged', 0)}  "
              f"Missing section: {counts.get('missing_section', 0)}")
    else:
        print(f"Written: {counts.get('written', 0)}  "
              f"Skipped (missing section): {counts.get('missing_section', 0)}")


def _section_anchor(section: str) -> str:
    """Convert a section heading to a GitHub markdown anchor.

    '## CC Skill' → '#cc-skill'  (lowercase, spaces→hyphens, strip punctuation)
    """
    anchor = section.lower().replace(" ", "-")
    # GitHub strips most punctuation except hyphens and underscores
    anchor = re.sub(r"[^\w\-]", "", anchor)
    return f"#{anchor}"


def write_manifest(manifest: list[dict], output_root: Path, platform: str, version: str):
    """Write compilation manifest.

    - JSON → variant repo (machine-readable, tracked there)
    - MD load map → knowledgeforge-core root (human-navigable on GitHub)

    The MD lives in core so that relative links like `modules/02_builder.md#cc-skill`
    resolve correctly within the same GitHub repo. Cross-repo relative links don't
    work on GitHub, so the map must be co-located with the source modules.
    """
    ts = datetime.now(timezone.utc).isoformat()

    # --- JSON (machine-readable) → variant repo ---
    manifest_path = output_root / ".kf-compile-manifest.json"
    data = {
        "compiled_at": ts,
        "source": "knowledgeforge-core",
        "platform": platform,
        "version": version,
        "entries": manifest,
    }
    manifest_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # --- Markdown load map (human-navigable) → core repo root ---
    # Links are relative to CORE_ROOT, so `modules/02_builder.md#cc-skill`
    # resolves on GitHub without any path gymnastics.
    md_lines = [
        f"# KnowledgeForge Load Map — `{platform}`",
        f"",
        f"**Version:** `{version}`  **Compiled:** `{ts}`",
        f"",
        f"Each row shows one compiled output and the exact source section it was extracted from.",
        f"Click the source link to jump directly to that section in the module file.",
        f"",
        f"| Status | Output (variant repo) | Source module | Section |",
        f"|:---:|---|---|:---:|",
    ]

    for entry in manifest:
        status = entry.get("status", "")
        source = entry.get("source", "")
        section = entry.get("section", "full")
        output = entry.get("output", "")

        # Source link — relative from core repo root, GitHub resolves these natively.
        if section not in ("full", "copy") and source:
            anchor = _section_anchor(section)
            source_link = f"[`{source}`](modules/{source}{anchor})"
            section_label = f"`{section}`"
        elif section == "copy":
            source_link = f"`{source}`"
            section_label = "_verbatim_"
        else:
            source_link = f"[`{source}`](modules/{source})" if source else "—"
            section_label = "_full file_"

        badge = {
            "written": "✓", "unchanged": "·", "changed": "~",
            "missing_section": "⚠︎", "would_write": "?",
        }.get(status, status)

        output_cell = f"`{output}`" if output else "—"
        md_lines.append(f"| {badge} | {output_cell} | {source_link} | {section_label} |")

    md_lines += [
        "",
        "---",
        f"_Generated by `compiler/kf-compile.py`. Do not edit manually._",
        f"_JSON manifest (machine-readable) is at `.kf-compile-manifest.json` in the variant repo._",
    ]

    # Write to core root so relative links resolve on GitHub.
    # Named without a dot prefix so it's visible in GitHub's file listing.
    md_path = CORE_ROOT / f"load-map-{platform}.md"
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    print(f"Manifest written:  {manifest_path}")
    print(f"Load map written:  {md_path}")


# ---------------------------------------------------------------------------
# Version loader
# ---------------------------------------------------------------------------

def load_version() -> str:
    kf_yaml = CORE_ROOT / "kf.yaml"
    if kf_yaml.exists():
        with open(kf_yaml, encoding="utf-8") as f:
            data = yaml.safe_load(f)
            return str(data.get("version", "unknown"))
    return "unknown"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="KnowledgeForge compiler — core modules → variant repos"
    )
    parser.add_argument(
        "--target",
        required=True,
        choices=["claude-code", "claude-projects", "cowork"],
        help="Platform target to compile for",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to the target variant repo root",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be written without writing",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Show what has changed vs. current output repo (no writes)",
    )
    parser.add_argument(
        "--manifest",
        action="store_true",
        default=True,
        help="Write .kf-compile-manifest.json to output repo (default: true)",
    )
    args = parser.parse_args()

    if args.dry_run and args.diff:
        sys.stderr.write("[kf-compile] --dry-run and --diff are mutually exclusive\n")
        sys.exit(1)

    output_root = Path(args.output).resolve()
    if not output_root.exists():
        sys.stderr.write(f"[kf-compile] Output directory not found: {output_root}\n")
        sys.exit(2)

    version = load_version()
    binding = load_binding(args.target)

    if args.target == "claude-code":
        manifest = compile_claude_code(
            binding, output_root, args.dry_run, args.diff, version
        )
    elif args.target == "claude-projects":
        manifest = compile_claude_projects(
            binding, output_root, args.dry_run, args.diff, version
        )
    else:
        sys.stderr.write(f"[kf-compile] Target '{args.target}' not yet implemented\n")
        sys.exit(1)

    print_manifest(manifest, args.target, args.dry_run, args.diff)

    if not args.dry_run and not args.diff and args.manifest:
        write_manifest(manifest, output_root, args.target, version)

    # Exit 1 if any sections were missing (signals incomplete module annotations)
    missing = sum(1 for e in manifest if e["status"] == "missing_section")
    if missing:
        sys.stderr.write(
            f"\n[kf-compile] {missing} output(s) skipped due to missing sections.\n"
            f"Add '## CC Skill' / '## CC Doc' / '## CC Agent' sections to modules.\n"
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
