#!/usr/bin/env bash
# verify-deterministic-build.sh — Confirm that kf-compile.py produces identical
# output across two consecutive runs (no timestamp drift, no ordering non-determinism).
#
# Usage:
#   scripts/verify-deterministic-build.sh [--target TARGET] [CC_REPO_PATH] [CP_REPO_PATH]
#
#   TARGET defaults to both claude-code and claude-projects.
#   If repo paths are not provided, the standard sibling-directory convention is used:
#     CC: ../knowledgeforge-cc   (relative to knowledgeforge-core root)
#     CP: ../knowledgeforge-cp
#
# Exit codes:
#   0 — builds are byte-identical (excluding compile-header lines)
#   1 — builds differ (non-determinism detected)
#   2 — target repo missing or compile error
#
# Note: This script runs both builds into fresh temp directories and compares them.
# The working core repo is never modified. The comparison excludes compile-header
# lines (<!-- Generated by kf-compile ... -->) because those contain no timestamps
# (bead rxc) but let's filter them defensively in case future headers change.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMPILER="${CORE_ROOT}/compiler/kf-compile.py"

TARGET="${1:-all}"
shift 2>/dev/null || true

CC_REPO="${1:-${CORE_ROOT}/../knowledgeforge-cc}"
CP_REPO="${2:-${CORE_ROOT}/../knowledgeforge-cp}"

# Normalize
CC_REPO="$(cd "${CC_REPO}" 2>/dev/null && pwd)" || { echo "[verify] CC repo not found: ${CC_REPO}"; exit 2; }
CP_REPO="$(cd "${CP_REPO}" 2>/dev/null && pwd)" || { echo "[verify] CP repo not found: ${CP_REPO}"; exit 2; }

TMPDIR_A="$(mktemp -d)"
TMPDIR_B="$(mktemp -d)"
trap 'rm -rf "${TMPDIR_A}" "${TMPDIR_B}"' EXIT

run_compare() {
    local target="$1"
    local src_repo="$2"

    echo ""
    echo "=== Verifying determinism: ${target} ==="

    local out_a="${TMPDIR_A}/${target}"
    local out_b="${TMPDIR_B}/${target}"
    mkdir -p "${out_a}" "${out_b}"

    # Copy existing compiled output as baseline (so compile-to-empty doesn't count as diff).
    # rsync verbatim so file timestamps/perms don't interfere.
    rsync -a --quiet "${src_repo}/" "${out_a}/"
    rsync -a --quiet "${src_repo}/" "${out_b}/"

    # Build A
    python3 "${COMPILER}" --target "${target}" --output "${out_a}" \
        2>/dev/null || { echo "[verify] Build A failed for ${target}"; exit 2; }

    # Build B
    python3 "${COMPILER}" --target "${target}" --output "${out_b}" \
        2>/dev/null || { echo "[verify] Build B failed for ${target}"; exit 2; }

    # Diff — strip compile-header lines defensively, then compare.
    # grep -v exits 1 when no lines match, which is fine (all lines kept means
    # no headers = no churn). Use || true to avoid pipefail on grep -v.
    local diff_output
    diff_output="$(
        diff -rq \
            --exclude=".kf-compile-manifest.json" \
            --exclude="load-map-*.md" \
            <(find "${out_a}" -type f | sort | xargs grep -l '' | xargs -I{} \
                grep -v '^<!-- Generated by kf-compile' {} 2>/dev/null || true) \
            <(find "${out_b}" -type f | sort | xargs grep -l '' | xargs -I{} \
                grep -v '^<!-- Generated by kf-compile' {} 2>/dev/null || true) \
        2>&1
    )" || true

    # Simpler, more reliable approach: diff the actual files directly.
    local diff_result
    diff_result="$(diff -rq \
        --exclude=".kf-compile-manifest.json" \
        "${out_a}" "${out_b}" 2>&1)" || {
        echo "[verify] FAIL — ${target} builds differ:"
        echo "${diff_result}"
        return 1
    }

    echo "[verify] PASS — ${target} builds are byte-identical."
    return 0
}

FAILED=0

if [[ "${TARGET}" == "all" || "${TARGET}" == "claude-code" ]]; then
    run_compare "claude-code" "${CC_REPO}" || FAILED=1
fi

if [[ "${TARGET}" == "all" || "${TARGET}" == "claude-projects" ]]; then
    run_compare "claude-projects" "${CP_REPO}" || FAILED=1
fi

echo ""
if [[ "${FAILED}" -eq 0 ]]; then
    echo "All targets: deterministic. ✓"
    exit 0
else
    echo "FAIL: one or more targets are non-deterministic. See above."
    exit 1
fi
